FROM gcr.io/cloud-builders/gcloud

# デプロイ先のプロジェクトID
ARG PROJECT_ID
# サービスアカウントのキーファイル名
ARG KEY_FILE_NAME
# サービスアカウントID
ARG SERVICE_ACCOUNT_ID

# デプロイ時の環境設定
ENV PROJECT_ID=${PROJECT_ID} \
    ACCOUNT=${SERVICE_ACCOUNT_ID} \
    KEY_FILE_NAME=${KEY_FILE_NAME}

# サービスアカウントのキーファイルを、Dockerコンテナ内にコピーする
COPY ${KEY_FILE_NAME} /${KEY_FILE_NAME}

WORKDIR /workspace

# デプロイスクリプトの実行
ENTRYPOINT ["sh"]
CMD ["deploy.sh"]